trigger:
  branches:
    include:
      - main

name: $(Date:yyyyMMdd)_$(Rev:.r)

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build_code
    displayName: Build code
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: CmdLine@2
            displayName: yarn install
            inputs:
              script: |
                echo yarn install
                yarn install
              workingDirectory: "$(Build.SourcesDirectory)"
            continueOnError: true
          - task: CmdLine@2
            displayName: yarn lint
            inputs:
              script: |
                yarn run lint
              workingDirectory: "$(Build.SourcesDirectory)"
            continueOnError: false
          - task: CmdLine@2
            displayName: build Artifact
            inputs:
              script: |
                yarn run build
              workingDirectory: "$(Build.SourcesDirectory)"
            continueOnError: false
          - task: CmdLine@2
            displayName: Publish Artifact
            inputs:
              script: |
                yarn publish
              workingDirectory: "$(Build.SourcesDirectory)"
            continueOnError: false
